### ISSUE TITLE
Error: Can't Get App's External Cache Dir

### ISSUE THREAD

**Issue by mrtaxi** [catpuppyapp/SshKeyMan#1]
Android,14, OnePlus 12. App can't start.

**Comment by Bandeapart1964** [comment]
I'll check

**Comment by Bandeapart1964** [comment]
does your phone has a path like /stroage/emulated/0 ?
I tested on android 14, is fine

**Comment by Bandeapart1964** [comment]
try new version: https://github.com/catpuppyapp/SshKeyMan/releases/tag/1.4v5

this version will try get the app inner cache dir if get external failed, if still can't work, tell me.

and I want to know maybe you use some app limit access the external dir /storage/emualted/0/Android/data folder?

**Comment by mrtaxi** [comment]
This version is working fine. Thank you!
